Prefix: "&eServerName &8| "
NoPermission: "&cNo permission, This server is using ToggleRank v0.1 by 9m8"
RankShown: "&aRank shown!"
RankHidden: "&cRank hidden!"
ShownRankChatFormat: "$prefix$player &8»&f "
HiddenRankChatFormat: "&9Member &8|&9 $player &8»&f "
TabChangeCommand: "nte player $p prefix &9"
TabPriorityCommand: "nte player $p priority 100"
TabClear: "nte player $p clear"